### ISSUE TITLE
Panic when manifest begins with a YAML inline schema string or a comment

### ISSUE THREAD

**Issue by netops2devops** [anderseknert/kube-review#51]
Hi @anderseknert 👋  `kube-review` has been a game changer for me in terms of developer experience and productivity when writing OPA policies so truly appreciate you supporting this tool. 🙏  I am trying to create an admission review JSON blob using `kube-review` with the following manifest which contains an inline schema. 

```yaml
# yaml-language-server: $schema=../.schemas/ciliumbgppeerconfig.json
---
apiVersion: isovalent.com/v1alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer-leaf16
spec:
  ebgpMultihop: 3
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv6
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
```

When I run `kube-review create manifest.yaml` I get the following error 

```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/anderseknert/kube-review/pkg/admission.fromUnstructured({0x140003b8000, 0x17d, 0x200}, 0x14000123b70, {0x1039eb9e7, 0xb}, {0x104782380, 0x0, 0x0}, 0x2)
	/home/kubedev/go/pkg/mod/github.com/anderseknert/kube-review@v0.4.0/pkg/admission/review.go:76 +0x544
github.com/anderseknert/kube-review/pkg/admission.CreateAdmissionReviewRequest({0x140003b8000, 0x17d, 0x200}, {0x1039e85e5?, 0x0?}, {0x1039eb9e7, 0xb}, {0x104782380, 0x0, 0x0}, ...)
	/home/kubedev/go/pkg/mod/github.com/anderseknert/kube-review@v0.4.0/pkg/admission/review.go:37 +0x398
github.com/anderseknert/kube-review/cmd.init.func1(0x14000176b00?, {0x14000123b60?, 0x4?, 0x1039e7e68?})
	/home/kubedev/go/pkg/mod/github.com/anderseknert/kube-review@v0.4.0/cmd/main.go:63 +0x1f4
github.com/spf13/cobra.(*Command).execute(0x104746e20, {0x14000123b20, 0x1, 0x1})
	/home/kubedev/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0x818
github.com/spf13/cobra.(*Command).ExecuteC(0x104746b40)
	/home/kubedev/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/kubedev/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/anderseknert/kube-review/cmd.Execute()
	/home/kubedev/go/pkg/mod/github.com/anderseknert/kube-review@v0.4.0/cmd/main.go:110 +0x160
main.main()
	/home/kubedev/go/pkg/mod/github.com/anderseknert/kube-review@v0.4.0/main.go:13 +0x4c
```

kube-review works fine when the first line is not a comment which in this case removing the inline schema from the manifest file.
